version: 1 # allow to specify the version of the code this is useful so service workers recache the new files

plugins:
  - jekyll-seo-tag

accent-color: 26a69a #hex color value
faded-accent-color: 1d8c81 #hex color value this is used for background when app is launching

sidenav-width: 300px # set to 300px for a enabled sidebar or 0 to diable the sidebar
custom-alignment: true # weather to use the custom alignment styles

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    #line_numbers: table
    wrap: false
    span:
      line_numbers: false