remote_theme: "godalming123/matirlize-jekyll-theme"
accent-color: 26a69a #hex color value
faded-accent-color: 1d8c81 #hex color value this is used for background when app is launching
sidenav-width: 300px;
custom-alignment: true;